- name: Install and configure IdM server
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Create NS
      community.okd.k8s:
        host: "{{ ocp_api }}"
        validate_certs: false
        api_key: "{{ ocp_token }}"
        state: present
        definition: "{{ lookup('template', 'ocp-ns.yml.j2') | from_yaml }}"
        validate:
          fail_on_error: no
          strict: yes
    - name: Create PV
      community.okd.k8s:
        host: "{{ ocp_api }}"
        validate_certs: false
        api_key: "{{ ocp_token }}"
        state: present
        definition: "{{ lookup('template', 'ocp-pv.yml.j2') | from_yaml }}"
        validate:
          fail_on_error: no
          strict: yes
    - name: Create PVC
      community.okd.k8s:
        host: "{{ ocp_api }}"
        validate_certs: false
        api_key: "{{ ocp_token }}"
        state: present
        definition: "{{ lookup('template', 'ocp-pvc.yml.j2') | from_yaml }}"
        validate:
          fail_on_error: no
          strict: yes
    - name: Create SCC
      community.okd.k8s:
        host: "{{ ocp_api }}"
        validate_certs: false
        api_key: "{{ ocp_token }}"
        state: present
        definition: "{{ lookup('template', 'ocp-scc.yml.j2') | from_yaml }}"
        validate:
          fail_on_error: no
          strict: yes
    - name: Create RoleBinding
      community.okd.k8s:
        host: "{{ ocp_api }}"
        validate_certs: false
        api_key: "{{ ocp_token }}"
        state: present
        definition: "{{ lookup('template', 'ocp-rb.yml.j2') | from_yaml }}"
        validate:
          fail_on_error: no
          strict: yes        
    - name: Create Deploy
      community.okd.k8s:
        host: "{{ ocp_api }}"
        validate_certs: false
        api_key: "{{ ocp_token }}"
        state: present
        definition: "{{ lookup('template', 'ocp-deploy.yml.j2') | from_yaml }}"
        validate:
          fail_on_error: no
          strict: yes