- name: Install and configure IdM server
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Create MCP
      community.okd.k8s:
        host: "{{ ocp_api }}"
        validate_certs: false
        api_key: "{{ ocp_token }}"
        state: present
        definition: "{{ lookup('template', 'ocp-mcp.yml.j2') | from_yaml }}"
        validate:
          fail_on_error: no
          strict: yes